### PR TITLE
Fix bug in auxiliary test case compilation in TestCommand

### LINKED ISSUE #10: bug: unable to correctly recognize and de-duplicate auxiliary files
It can only match the auxiliary file declared in the testcase in the first line of the “aux-build” comment, and there is no de-duplication of the auxiliary file. `./y test -v` and part of output is here:
```bash
[TEST] found 7 testcases 
       compile-lib: auxiliary/mini_core
       compile-lib: auxiliary/mini_core
       compile: examples/basic_math
       filecheck: codegen/filename
       filecheck: codegen/params_count
       filecheck: codegen/ret_value
       bless: bless/basic_math
```

### PR DESCRIPTION
**Pull request by xizheyin**
Fixes #10 .

### CODE REVIEW

File: bootstrap/src/test.rs [hunk 1]
```diff
@@ -114,30 +114,36 @@ impl TestCommand {
...
+            cases.push(testcase);
         }
 
         // Collect test-auxiliary
-        let aux_use = regex::Regex::new(r"^//@\s*aux-build:(?P<fname>.*)").unwrap();
-        let mut auxiliary = vec![];
-        for case in tests.iter() {
-            let source = std::fs::read_to_string(&case.source).unwrap();
-            for cap in aux_use.captures_iter(&source) {
+        let aux_use = regex::Regex::new(r"\s*//@\s*aux-build:(?P<fname>.*)").unwrap();
```
Comment (tgross35) [inline bootstrap/src/test.rs]: Should probably keep the start anchor, we don't want to accept directives that come after other content

```suggestion
        let aux_use = regex::Regex::new(r"^\s*//@\s*aux-build:(?P<fname>.*)").unwrap();
```

Comment (xizheyin) [reply bootstrap/src/test.rs]: Some testcases like `tests/codegen/filename.rs` declare `aux-build` in the third line.

```
//! Test that the generated code has the filename and function name in it

//@ aux-build:mini_core.rs

// CHECK: filename
...
```

Comment (tgross35) [reply bootstrap/src/test.rs]: Ah, the regex should probably start with `(?m)` to enable multi-line mode. Or iterate `.lines()` and check each separately.

Comment (xizheyin) [reply bootstrap/src/test.rs]: I solved it.
